package net.webservicex;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.9
 * 2018-02-22T22:35:46.769-06:00
 * Generated source version: 3.1.9
 * 
 */
@WebService(targetNamespace = "http://www.webserviceX.NET", name = "countrySoap")
@XmlSeeAlso({ObjectFactory.class})
public interface CountrySoap {

    /**
     * Get all currency,currency code for all countries 
     */
    @WebMethod(operationName = "GetCurrencies", action = "http://www.webserviceX.NET/GetCurrencies")
    @RequestWrapper(localName = "GetCurrencies", targetNamespace = "http://www.webserviceX.NET", className = "net.webservicex.GetCurrencies")
    @ResponseWrapper(localName = "GetCurrenciesResponse", targetNamespace = "http://www.webserviceX.NET", className = "net.webservicex.GetCurrenciesResponse")
    @WebResult(name = "GetCurrenciesResult", targetNamespace = "http://www.webserviceX.NET")
    public String getCurrencies();

    /**
     * Get International Dialing Code by country name 
     */
    @WebMethod(operationName = "GetISD", action = "http://www.webserviceX.NET/GetISD")
    @RequestWrapper(localName = "GetISD", targetNamespace = "http://www.webserviceX.NET", className = "net.webservicex.GetISD")
    @ResponseWrapper(localName = "GetISDResponse", targetNamespace = "http://www.webserviceX.NET", className = "net.webservicex.GetISDResponse")
    @WebResult(name = "GetISDResult", targetNamespace = "http://www.webserviceX.NET")
    public String getISD(
            @WebParam(name = "CountryName", targetNamespace = "http://www.webserviceX.NET")
                    String countryName
    );

    /**
     * Get country by currency code
     */
    @WebMethod(operationName = "GetCountryByCurrencyCode", action = "http://www.webserviceX.NET/GetCountryByCurrencyCode")
    @RequestWrapper(localName = "GetCountryByCurrencyCode", targetNamespace = "http://www.webserviceX.NET", className = "net.webservicex.GetCountryByCurrencyCode")
    @ResponseWrapper(localName = "GetCountryByCurrencyCodeResponse", targetNamespace = "http://www.webserviceX.NET", className = "net.webservicex.GetCountryByCurrencyCodeResponse")
    @WebResult(name = "GetCountryByCurrencyCodeResult", targetNamespace = "http://www.webserviceX.NET")
    public String getCountryByCurrencyCode(
            @WebParam(name = "CurrencyCode", targetNamespace = "http://www.webserviceX.NET")
                    String currencyCode
    );

    /**
     * Get countries by country name 
     */
    @WebMethod(operationName = "GetISOCountryCodeByCountyName", action = "http://www.webserviceX.NET/GetISOCountryCodeByCountyName")
    @RequestWrapper(localName = "GetISOCountryCodeByCountyName", targetNamespace = "http://www.webserviceX.NET", className = "net.webservicex.GetISOCountryCodeByCountyName")
    @ResponseWrapper(localName = "GetISOCountryCodeByCountyNameResponse", targetNamespace = "http://www.webserviceX.NET", className = "net.webservicex.GetISOCountryCodeByCountyNameResponse")
    @WebResult(name = "GetISOCountryCodeByCountyNameResult", targetNamespace = "http://www.webserviceX.NET")
    public String getISOCountryCodeByCountyName(
            @WebParam(name = "CountryName", targetNamespace = "http://www.webserviceX.NET")
                    String countryName
    );

    /**
     * Get all currencycode for each country 
     */
    @WebMethod(operationName = "GetCurrencyCode", action = "http://www.webserviceX.NET/GetCurrencyCode")
    @RequestWrapper(localName = "GetCurrencyCode", targetNamespace = "http://www.webserviceX.NET", className = "net.webservicex.GetCurrencyCode")
    @ResponseWrapper(localName = "GetCurrencyCodeResponse", targetNamespace = "http://www.webserviceX.NET", className = "net.webservicex.GetCurrencyCodeResponse")
    @WebResult(name = "GetCurrencyCodeResult", targetNamespace = "http://www.webserviceX.NET")
    public String getCurrencyCode();

    /**
     * Get currency by country name 
     */
    @WebMethod(operationName = "GetCurrencyByCountry", action = "http://www.webserviceX.NET/GetCurrencyByCountry")
    @RequestWrapper(localName = "GetCurrencyByCountry", targetNamespace = "http://www.webserviceX.NET", className = "net.webservicex.GetCurrencyByCountry")
    @ResponseWrapper(localName = "GetCurrencyByCountryResponse", targetNamespace = "http://www.webserviceX.NET", className = "net.webservicex.GetCurrencyByCountryResponse")
    @WebResult(name = "GetCurrencyByCountryResult", targetNamespace = "http://www.webserviceX.NET")
    public String getCurrencyByCountry(
            @WebParam(name = "CountryName", targetNamespace = "http://www.webserviceX.NET")
                    String countryName
    );

    /**
     * Get all countries with ISO code
     */
    @WebMethod(operationName = "GetCountries", action = "http://www.webserviceX.NET/GetCountries")
    @RequestWrapper(localName = "GetCountries", targetNamespace = "http://www.webserviceX.NET", className = "net.webservicex.GetCountries")
    @ResponseWrapper(localName = "GetCountriesResponse", targetNamespace = "http://www.webserviceX.NET", className = "net.webservicex.GetCountriesResponse")
    @WebResult(name = "GetCountriesResult", targetNamespace = "http://www.webserviceX.NET")
    public String getCountries();

    /**
     * Get currency by currency name 
     */
    @WebMethod(operationName = "GetCurrencyCodeByCurrencyName", action = "http://www.webserviceX.NET/GetCurrencyCodeByCurrencyName")
    @RequestWrapper(localName = "GetCurrencyCodeByCurrencyName", targetNamespace = "http://www.webserviceX.NET", className = "net.webservicex.GetCurrencyCodeByCurrencyName")
    @ResponseWrapper(localName = "GetCurrencyCodeByCurrencyNameResponse", targetNamespace = "http://www.webserviceX.NET", className = "net.webservicex.GetCurrencyCodeByCurrencyNameResponse")
    @WebResult(name = "GetCurrencyCodeByCurrencyNameResult", targetNamespace = "http://www.webserviceX.NET")
    public String getCurrencyCodeByCurrencyName(
            @WebParam(name = "CurrencyName", targetNamespace = "http://www.webserviceX.NET")
                    String currencyName
    );

    /**
     * Get greenwich mean time(GMT) by country name 
     */
    @WebMethod(operationName = "GetGMTbyCountry", action = "http://www.webserviceX.NET/GetGMTbyCountry")
    @RequestWrapper(localName = "GetGMTbyCountry", targetNamespace = "http://www.webserviceX.NET", className = "net.webservicex.GetGMTbyCountry")
    @ResponseWrapper(localName = "GetGMTbyCountryResponse", targetNamespace = "http://www.webserviceX.NET", className = "net.webservicex.GetGMTbyCountryResponse")
    @WebResult(name = "GetGMTbyCountryResult", targetNamespace = "http://www.webserviceX.NET")
    public String getGMTbyCountry(
            @WebParam(name = "CountryName", targetNamespace = "http://www.webserviceX.NET")
                    String countryName
    );

    /**
     * Get country name by country code
     */
    @WebMethod(operationName = "GetCountryByCountryCode", action = "http://www.webserviceX.NET/GetCountryByCountryCode")
    @RequestWrapper(localName = "GetCountryByCountryCode", targetNamespace = "http://www.webserviceX.NET", className = "net.webservicex.GetCountryByCountryCode")
    @ResponseWrapper(localName = "GetCountryByCountryCodeResponse", targetNamespace = "http://www.webserviceX.NET", className = "net.webservicex.GetCountryByCountryCodeResponse")
    @WebResult(name = "GetCountryByCountryCodeResult", targetNamespace = "http://www.webserviceX.NET")
    public String getCountryByCountryCode(
            @WebParam(name = "CountryCode", targetNamespace = "http://www.webserviceX.NET")
                    String countryCode
    );
}
