package net.webservicex;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.9
 * 2018-02-22T22:35:46.766-06:00
 * Generated source version: 3.1.9
 * 
 */
@WebService(targetNamespace = "http://www.webserviceX.NET", name = "countryHttpGet")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface CountryHttpGet {

    /**
     * Get all currency,currency code for all countries 
     */
    @WebMethod(operationName = "GetCurrencies")
    @WebResult(name = "string", targetNamespace = "http://www.webserviceX.NET", partName = "Body")
    public String getCurrencies();

    /**
     * Get International Dialing Code by country name 
     */
    @WebMethod(operationName = "GetISD")
    @WebResult(name = "string", targetNamespace = "http://www.webserviceX.NET", partName = "Body")
    public String getISD(
            @WebParam(partName = "CountryName", name = "CountryName", targetNamespace = "")
                    String countryName
    );

    /**
     * Get country by currency code
     */
    @WebMethod(operationName = "GetCountryByCurrencyCode")
    @WebResult(name = "string", targetNamespace = "http://www.webserviceX.NET", partName = "Body")
    public String getCountryByCurrencyCode(
            @WebParam(partName = "CurrencyCode", name = "CurrencyCode", targetNamespace = "")
                    String currencyCode
    );

    /**
     * Get countries by country name 
     */
    @WebMethod(operationName = "GetISOCountryCodeByCountyName")
    @WebResult(name = "string", targetNamespace = "http://www.webserviceX.NET", partName = "Body")
    public String getISOCountryCodeByCountyName(
            @WebParam(partName = "CountryName", name = "CountryName", targetNamespace = "")
                    String countryName
    );

    /**
     * Get all currencycode for each country 
     */
    @WebMethod(operationName = "GetCurrencyCode")
    @WebResult(name = "string", targetNamespace = "http://www.webserviceX.NET", partName = "Body")
    public String getCurrencyCode();

    /**
     * Get currency by country name 
     */
    @WebMethod(operationName = "GetCurrencyByCountry")
    @WebResult(name = "string", targetNamespace = "http://www.webserviceX.NET", partName = "Body")
    public String getCurrencyByCountry(
            @WebParam(partName = "CountryName", name = "CountryName", targetNamespace = "")
                    String countryName
    );

    /**
     * Get all countries with ISO code
     */
    @WebMethod(operationName = "GetCountries")
    @WebResult(name = "string", targetNamespace = "http://www.webserviceX.NET", partName = "Body")
    public String getCountries();

    /**
     * Get currency by currency name 
     */
    @WebMethod(operationName = "GetCurrencyCodeByCurrencyName")
    @WebResult(name = "string", targetNamespace = "http://www.webserviceX.NET", partName = "Body")
    public String getCurrencyCodeByCurrencyName(
            @WebParam(partName = "CurrencyName", name = "CurrencyName", targetNamespace = "")
                    String currencyName
    );

    /**
     * Get greenwich mean time(GMT) by country name 
     */
    @WebMethod(operationName = "GetGMTbyCountry")
    @WebResult(name = "string", targetNamespace = "http://www.webserviceX.NET", partName = "Body")
    public String getGMTbyCountry(
            @WebParam(partName = "CountryName", name = "CountryName", targetNamespace = "")
                    String countryName
    );

    /**
     * Get country name by country code
     */
    @WebMethod(operationName = "GetCountryByCountryCode")
    @WebResult(name = "string", targetNamespace = "http://www.webserviceX.NET", partName = "Body")
    public String getCountryByCountryCode(
            @WebParam(partName = "CountryCode", name = "CountryCode", targetNamespace = "")
                    String countryCode
    );
}
